[General]
Name=MMConfig_Clear
HookChildProcesses=1
HintingMode=1
AntiAliasMode=2
NormalWeight=0
BoldWeight=0
ItalicSlant=-2
UseMapping=0
GammaMode=0
GammaValue=2.2
Contrast=1.0
RenderWeight=1.1
TextTuning=0
TextTuningR=0
TextTuningG=0
TextTuningB=0
BolderMode=2
FontLoader=0
Fontlink=2
FontSubstitutes=1
MaxHeight=0
LcdFilter=2
LoadOnDemand=1
CacheMaxFaces=256
CacheMaxSizes=33554432
CacheMaxBytes=67108864
EnableKerning=1
MaxBitmap=0
HintSmallFont=1
DirectWrite=1
Shadow=1,1,0,0x0,0,0x0 

[exclude]


[FontSubstitutes]

[Preview]
Font=Microsoft Yahei
Color=$435ACD
Text=MMConfig Clear
Size=12
Align=Center

[DirectWrite]
RenderingMode= 5
ClearTypeLevel = 0.95
Contrast = 0.12

[Individual]
; 1st pos: normal weight
; 2nd pos: bold weight
Microsoft YaHei=,,0,-7,,
Microsoft YaHei UI=,,0,-7,,

[ExcludeSub]
ModernWarfare.exe
Borderlands3.exe

; The bug of touhou series was solved.
[UnloadDll]
ModernWarfare.exe
Adobe Premiere Pro.exe
Adobe Spaces Helper.exe
AfterFX.exe
Photoshop.exe
CEPHtmlEngine.exe
Illustrator.exe
InDesign.exe
Terraria.dll
zerotier.exe
zerotier_desktop_ui.exe
MsiExec.exe

[experimental]
Colorfont=1
[Experimental@chrome.exe]
invertcolor=1
[General@chrome.exe]
RenderWeight=0.8
[General@QQ.exe]
NormalWeight=1
BoldWeight=-0.2
[Experimental@idea64.exe]
; Workaround for IDEA/JAVA font rendering unverified as of 2018/10/19
clipboxfix=1